# HF_TOKEN is automatically injected from Secret Manager (see availableSecrets below)
# DO NOT pass HF_TOKEN via --substitutions when running gcloud builds submit
# User-defined substitutions must start with underscore (e.g., _MY_VAR)
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: load-config
  entrypoint: 'bash'
  args:
    - -c
    - |
        # Load configuration from config.env and export as Cloud Build substitutions
        source config.env
        echo "SERVICE_NAME=$SERVICE_NAME" > /workspace/build_config.env
        echo "ARTIFACT_REGISTRY_REPO=$ARTIFACT_REGISTRY_REPO" >> /workspace/build_config.env
        echo "ARTIFACT_REGISTRY_IMAGE=$ARTIFACT_REGISTRY_IMAGE" >> /workspace/build_config.env
        cat /workspace/build_config.env

- name: 'gcr.io/cloud-builders/docker'
  id: build
  waitFor: ['load-config']
  entrypoint: 'bash'
  secretEnv: ['HF_TOKEN']
  env:
    # Set TORCH_CUDA_ARCH_LIST for the build environment
    # This helps prevent warnings about compiling for all architectures
    - 'TORCH_CUDA_ARCH_LIST=7.5'
  args:
    - -c
    - |
        # Load config
        source /workspace/build_config.env
        IMAGE="us-central1-docker.pkg.dev/${PROJECT_ID}/$ARTIFACT_REGISTRY_REPO/$ARTIFACT_REGISTRY_IMAGE"

        # Pass TORCH_CUDA_ARCH_LIST as a build arg to the Docker build
        docker buildx build \
          --tag=$IMAGE \
          --secret id=HF_TOKEN,env=HF_TOKEN \
          --build-arg TORCH_CUDA_ARCH_LIST=7.5 \
          .
        # Push the image to Artifact Registry
        docker push $IMAGE

        # Save IMAGE for subsequent steps
        echo "IMAGE=$IMAGE" > /workspace/image_path.env

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: deploy
  waitFor: ['build']
  entrypoint: 'bash'
  args:
    - -c
    - |
        # Load config
        source /workspace/build_config.env
        source /workspace/image_path.env

        # Deploy to Cloud Run with dynamic service name
        gcloud run deploy "$SERVICE_NAME" \
          --image="$IMAGE" \
          --region=us-central1 \
          --platform=managed \
          --execution-environment=gen2 \
          --cpu=8 \
          --memory=32Gi \
          --gpu=1 \
          --gpu-type=nvidia-l4 \
          --no-cpu-throttling \
          --timeout=600 \
          --concurrency=1 \
          --min-instances=1 \
          --max-instances=3 \
          --cpu-boost \
          --port=8080 \
          --startup-probe=httpGet.path=/health,httpGet.port=8080,initialDelaySeconds=30,periodSeconds=10,timeoutSeconds=10,failureThreshold=30

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: test
  waitFor: ['deploy']
  entrypoint: 'bash'
  args:
    - -c
    - |
      # Install Python 3.13
      apt-get update && apt-get install -y python3.13 python3.13-venv python3-pip
      # Use Python 3.13 for tests
      python3.13 -m pip install -r requirements-test.txt
      python3.13 -m pytest test_endpoint.py -v

availableSecrets:
  secretManager:
  - versionName: 'projects/${PROJECT_ID}/secrets/HF_TOKEN/versions/latest'
    env: 'HF_TOKEN'

# Note: Image path is constructed from config.env at build time
# Format: us-central1-docker.pkg.dev/PROJECT_ID/ARTIFACT_REGISTRY_REPO/ARTIFACT_REGISTRY_IMAGE

options:
  machineType: "E2_HIGHCPU_8"
  diskSizeGb: 200
  logging: CLOUD_LOGGING_ONLY
