# HF_TOKEN is automatically injected from Secret Manager (see availableSecrets below)
# DO NOT pass HF_TOKEN via --substitutions when running gcloud builds submit
# User-defined substitutions must start with underscore (e.g., _MY_VAR)
steps:
- name: 'gcr.io/cloud-builders/docker'
  id: build
  entrypoint: 'bash'
  secretEnv: ['HF_TOKEN']
  env:
    # Set TORCH_CUDA_ARCH_LIST for the build environment
    # This helps prevent warnings about compiling for all architectures
    - 'TORCH_CUDA_ARCH_LIST=7.5'
  args:
    - -c
    - |
        # Pass TORCH_CUDA_ARCH_LIST as a build arg to the Docker build
        docker buildx build \
          --tag=${_IMAGE} \
          --secret id=HF_TOKEN,env=HF_TOKEN \
          --build-arg TORCH_CUDA_ARCH_LIST=7.5 \
          .

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: deploy
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', 'vllm-deepseek-r1',
    '--image', '${_IMAGE}',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--execution-environment', 'gen2',
    # Resource allocation for GPU workloads
    '--cpu', '8',
    '--memory', '32Gi',
    '--gpu', '1',
    '--gpu-type', 'nvidia-l4',
    # Performance and scaling configuration
    '--timeout', '600',
    '--concurrency', '1',
    '--min-instances', '1',
    '--max-instances', '10',
    # Startup probe configuration (prevents routing requests before ready)
    '--cpu-boost',
    '--startup-probe', 'httpGet.path=/health,httpGet.port=8000,initialDelaySeconds=10,periodSeconds=10,timeoutSeconds=5,failureThreshold=60'
  ]

- name: 'python:3.9-slim'
  id: install-dependencies
  entrypoint: 'pip'
  args: ['install', '-r', 'requirements-test.txt']

- name: 'python:3.9-slim'
  id: test
  entrypoint: 'pytest'
  args: ['test_endpoint.py']

availableSecrets:
  secretManager:
  - versionName: 'projects/${PROJECT_ID}/secrets/HF_TOKEN/versions/latest'
    env: 'HF_TOKEN'

images: ["${_IMAGE}"]

substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/vllm-deepseek-r1-repo/vllm-deepseek-r1'

options:
  dynamicSubstitutions: true
  machineType: "E2_HIGHCPU_32"
  diskSizeGb: 200
  logging: CLOUD_LOGGING_ONLY
